[graph]
exclude-dev = true

[bans]
deny = [
    { crate = "rex-test-utils", reason = "test utils can only be used in dev deps" },
]

# allow multiple versions for now.
# This shows findings for multiple
# versions of the same package pulled in as a dependency.
multiple-versions = "allow"
