name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add swap space
      run: |
        sudo swapoff /swapfile || true
        sudo rm -f /swapfile
        sudo fallocate -l 8G /swapfile
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile

    - name: Build
      run: cargo build --workspace --release

    - name: Run tests
      run: cargo test --workspace --release
